config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'

  get 'likes/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  root "sessions#new"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "home", to: "static_pages#home"
  post "/login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :likes, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li class="footer-about"><%= link_to "about", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fix-top">
  <div class="container">
    <nav>
      <%= link_to "Microblog", "#", id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="search-nav">
            <%= form_tag(home_path, method: :get) do %>
              <div class="input-group">
                <%= search_field_tag "q", params[:q], class: "form-control", placeholder: "キーワード検索" %>
                <span class="input-group-btn">
                  <%= submit_tag "検索", class: "btn btn-default" %>
                </span>
              </div>
            <% end %>
          </li>
          <li><%= link_to "home", home_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", root_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microblog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Vollkorn" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>
  <body>
    <div class="container">
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>